[package]
name = "meshlite_ffi"
version = "0.1.0"
authors = ["Jeremy HU <huxingyi@msn.com>", "anderejd <https://github.com/anderejd>"]

[lib]
name = "meshlite_ffi"
crate-type = ["cdylib"]

[dependencies]
cgmath = "0.16"
meshlite = { path = "../" }

